### ISSUE TITLE
./zhang-xie/SoftwareAnalyticsInPractice.md

### ISSUE THREAD

**Issue by trevorcarnahan** [ds4se/chapters#100]
## Title of chapter

_Software Analytics in Practice_
## URL to the chapter

_https://github.com/ds4se/chapters/blob/master/zhang-xie/SoftwareAnalyticsInPractice.md_
## Message?

_Software Analytics can help eng. productivity, product quality, and user experience by producing actionable insights in practice._
## Accessible?

_Yes, the content was accessible to the generalist._
## Size?

_The chapter is a good length._

_I struggled a bit with the flow of the sections. I'm not sure why "Research Topic" is in the "in Practice" chapter, it stands out a bit.  Maybe if the title clarified this was from the researcher point of view it would be clearer._

_Consider less discussion of what Software Analytics is (since it is heavily covered by the rest of the chapters/book) and more content, with specific examples or story, on your experience putting it into practice with the business impact of it to set the hook._
## Gotta Mantra?

_Nothing is jumping to mind here… maybe something like:_
_Putting Software Analytics Research into Practice_
_Help my Software Analytics Research Resonate with Practice_
## Best Points

_I liked the last section on your experiences and "Evaluation criteria tied with real tasks…" (results) and the example it gave.  This was a good concrete example of connection to practice._

**Comment by tzimmermsr** [comment]
Moved to #90
