### ISSUE TITLE
./obaysal/personalization-chapter.md

### ISSUE THREAD

**Issue by margaretstorey** [ds4se/chapters#104]

**Comment by margaretstorey** [comment]
## Title of chapter

_A Tailored Suit: The Big Opportunity in Personalizing Issue Tracking_

## URL to the chapter

_https://github.com/ds4se/chapters/blob/master/obaysal/personalization-chapter.md_

## Message?

What is the chapter's  clear and approachable take away message?

_Current issue tracking tools can be hard to use because they present too much information to developers, but they can be improved by personalizing the information they show to developers and thus improve situation awareness._

## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

_It is quite accessible, if the reader has some insights into issue trackers (which I assume most readers would).  But adding one more sentence about them may help._

## Size?

Is the chapter the right length?
Should anything missing be added?
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?
What are the aspects of the chapter that authors  SHOULD  change?

_It is quite short but within the guidelines. I think perhaps a bit more discussion about the challenges surrounding situational awareness could be helpful. A concluding paragraph would also be nice.  Perhaps be clear who the chapter is for -- it seems it is aimed at tool developers (issue tracker tool designers/researchers), is that right?  Or do you hope other stakeholders may care about this? If you aim this at other stakeholders, what advice do you have for them?_

## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

_The title does provide a mantra, and is catchy.  You could put dashboards in the title perhaps?_

## Best Points

What are the best points of the chapter that the authors should NOT change?

_I like the points for improvement at the end.  They are actionable._

**Comment by timm** [comment]
I think this chapter needs more specifics. how about:
- graphics showing samples of dashboards and a little lessons learned from each.

**Comment by obaysal** [comment]
Thank you @margaretstorey and @kimherzig for your insightful reviews! I have revised the chapter based on your comments. I have added a figure illustrating developer dashboards, elaborated more on what issue trackers and situational awareness mean, made the analogy better (thank you @kimherzig for your suggestions on that), added "developer dashboards" to the title of the chapter, added a para about overfitting and other smaller edits. 

@timm What do you think about the title? Too lengthy? 

@timm Sorry for keeping you waiting so long! You have been very patient with me, thank you for not giving up on me!

**Comment by timm** [comment]
@obaysal 
can we change title to "Issue Tracking: Many Choices, Nothing Great"

so you first sub-heading in the paper would be "need for personalization"

?

**Comment by obaysal** [comment]
@timm I am not sure if your title captures the insight of the chapter well. May be we can stick with the old one then - "A Tailored Suit: The Big Opportunity in Personalizing Issue Tracking".

**Comment by timm** [comment]
Done!
