### ISSUE TITLE
chapter to review

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#11]
this one has our names on it

https://github.com/ds4se/chapters/blob/master/menzies/inductiveManifesto.md

care to check it?

**Comment by tomFr** [comment]
Hi Tim,

sorry to ask, but I'm not sure if this is a general question or if that was directed to me and if so, what exactly would want me to do.

Cheers,
  Thomas

**Comment by minkull** [comment]
Hi Tim,

Same here!

Best,
Leandro

On 12 October 2015 at 08:53, tomFr notifications@github.com wrote:

> Hi Tim,
> 
> sorry to ask, but I'm not sure if this is a general question or if that
> was directed to me and if so, what exactly would want me to do.
> 
> Cheers,
> Thomas
> 
> On 11 Oct 2015, at 22:26, Tim Menzies notifications@github.com wrote:
> 
> > this one has our names on it
> > 
> > https://github.com/ds4se/chapters/blob/master/menzies/inductiveManifesto.md
> > 
> > care to check it?
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ds4se/chapters/issues/11#issuecomment-147319321.

## 

Dr. Leandro L. Minku
Lecturer (Assistant Professor) in Computer Science
Department of Computer Science
University of Leicester, UK
http://www.cs.le.ac.uk/people/llm11 http://www.cs.bham.ac.uk/~minkull
