### ISSUE TITLE
Identifying Fault-prone Files in Large Industrial Software Systems

### ISSUE THREAD

**Issue by GRuhe** [ds4se/chapters#110]
## URL to the chapter

_the markdown file. e.g. https://github.com/ds4se/chapters/blob/master/weyuker-ostrand/prediction.md_
## Message?

What is the chapter's  clear and approachable take away message?

_Accurate defect prediction IS possible_
## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

_Yes, it is written in a non-technical language, easy to understand also for non-experts_
## Size?

Is the chapter the right length?
Should anything missing be added?
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?
What are the aspects of the chapter that authors SHOULD  change?

_Length is right, no suggestion for changes. Would be nice to have one or two sentences if and how successful the results were used at AT&T._
## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

_Fault distribution among files follows the Pareto rule_
## Best Points

What are the best points of the chapter that the authors should NOT change?

_Starting with a (nice and to-the point) joke_

**Comment by tzimmermsr** [comment]
Moved the review to #88.
