### ISSUE TITLE
Reducing Time to Insight (T. Carnahan)

### ISSUE THREAD

**Issue by siravegas** [ds4se/chapters#112]
# Review template

Before filling in this review, please read our [Advice to Reviewers](how2review.md).

_(If you have confidential comments about this chapter, please email them to one of the book editors._)
## Title of chapter

_Reducing Time to Insight_
## URL to the chapter

_https://github.com/ds4se/chapters/blob/master/trevorcarnahan/Reducing%20Time%20to%20Insight.md_
## Message?

What is the chapter's  clear and approachable take away message?

_Producing insights faster to improve results faster. Avoiding being too late._
## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

_It is written for a generalist audience. It is already accessible._
## Size?

Is the chapter the right length?

_Yes._

Should anything missing be added?

_No._

Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?

_No._

What are the aspects of the chapter that authors  SHOULD  change?

_1. Perhaps the "what to do" section could be organised in a way that the different items can be related to each other. As they are now they are a bit confusing. A possibility could be organising them according to the phases identified in the figure._

_2. First paragraph of the chapter: "I'll assert are you are..."._
## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

_No need to change the title. Perhaps the author could consider adding something like: "Avoiding being too late" or something like that. Something that includes "too late" in the title._
## Best Points

What are the best points of the chapter that the authors should NOT change?

_In general, how the chapter has been written. I liked it all. The message is clear, and it is easy to understand._

**Comment by tzimmermsr** [comment]
Moved to #80.
