### ISSUE TITLE
Software Analytics in Practice (Zhang & Xie)

### ISSUE THREAD

**Issue by siravegas** [ds4se/chapters#113]
# Review template

Before filling in this review, please read our [Advice to Reviewers](how2review.md).

_(If you have confidential comments about this chapter, please email them to one of the book editors._)
## Title of chapter

_Software Analytics in Practice._
## URL to the chapter

_https://github.com/ds4se/chapters/blob/master/zhang-xie/SoftwareAnalyticsInPractice.md_
## Message?

What is the chapter's  clear and approachable take away message?

_The chapter describes what analytics involves in the software context as well as some experiences using it._
## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

_The paper is written for a generalist audience. It does not need to be made more accessible._
## Size?

Is the chapter the right length?

_Yes._

Should anything missing be added?

_An example at the beginning of the paper could make it more appealing._

Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?

_If the authors need more space when adding the example, the "research topic", "target audience" and "input" sections include information already mentioned at the beginning of the chapter._

What are the aspects of the chapter that authors  SHOULD  change?

_Already mentioned above._
## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

_The current title "Software Analytics in Practice" only reflects the contents of the last part of the chapter. According to the third paragraph of the chapter, it "discusses software analytics from six perspectives [...]. We also share our experiences on putting software analytics into practice"._

_Perhaps the title should reflect more accurately the contents of the chapter. When I started to read it, I expected something different from what I read. A possibility could be starting the title with something like "Data Analytics in the Software Domain", and then perhaps add something that helps understand better what the chapter is about (essential aspects to be taken into consideration or something like that)._
## Best Points

What are the best points of the chapter that the authors should NOT change?

_Definitely, the last section of the chapter (experiences on putting software analytics into practice) is the most useful one. It should not be changed at all._

**Comment by tzimmermsr** [comment]
Moved to #90.
