### ISSUE TITLE
Review of MERE NUMBERS AREN'T ENOUGH: A PLEA FOR VISUALIZATION

### ISSUE THREAD

**Issue by tostrand** [ds4se/chapters#118]
MERE NUMBERS AREN'T ENOUGH: A PLEA FOR VISUALIZATION

Very nice concept, I'm in complete agreement on the value of visualizing data, when it's done well.  The two examples are classic software engineering tasks that can be helped by appropriate visualization of relevant data.  

The presentation in the article needs some improvement. 

FEATURE SCOPING

"scope out" sounds strange (to my American ear).  It would be much easier to understand if "exclude" were used.  For example:

Replace "... which to scope out from the current project." 
with "... which to exclude from the current project. " 

scoped out -> excluded

I don't understand the phrase "basic average share of descoped features". 

The next sentence isn't really a sentence.  What didn't happen "until they presented the feature survival chart" ??  

Presumably Figure X means figure 1.
But the figure itself is confusing, and the text seems to be confused also.  The text seems to have the x and y-axes interchanged.  Aren't the features on the y-axis, and the milestones on the x-axis? 

Instead of "nuances of green", it would be better to say "shades of green".  
The paragraph just above the figure mentions the marked decision points numbered 1  through 5, but doesn't explain anything about what the decisions were, or how the feature scoping affected the decisions.  Even in this short overview article, at least a couple of sentences about the actual use of the chart would be helpful. 

REGRESSION TESTING

Presumably Figure Y means figure 2.

The picture looks colorful and nice, but without an explanation, I can only guess what the different colors mean. Does the first row mean that Unit Testing was done intensely on about 15 features in V 3.0, intensely on 2, and less intensely on 12 features in 3.2, and not at all in 3.3?

**Comment by tzimmermsr** [comment]
Review now in #73
