### ISSUE TITLE
Review of "Summarizing Dynamic Data" by Andreas Zeller

### ISSUE THREAD

**Issue by andreas-zeller** [ds4se/chapters#120]
## Title of chapter

Summarizing Dynamic Data
## URL to the chapter

https://github.com/ds4se/chapters/blob/master/rtholmes/summarizing-dynamic-data.md
## Message?

What is the chapter's  clear and approachable take away message?

_To summarize dynamic data, consider state transitions_
## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

_I am not sure whether the problem of bike shedding in empirical SE is sufficiently widespread to warrant this chapter; so more evidence and/or motivation would be welcome.  Likewise, I am not sure whether the solution of summarizing data into state transitions is sufficiently general to be framed as the one solution.  I would prefer having a concrete story (which is currently hidden in the chapter) on how state transitions saved a particular concrete project._
## Size?

Is the chapter the right length?
Should anything missing be added?
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?
What are the aspects of the chapter that authors  SHOULD  change?

_See above.  I can live with the chapter as is, but making it more of an anecdote would be both more compelling and justified._
## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

_Look for State Transitions in Temporal Data_
## Best Points

What are the best points of the chapter that the authors should NOT change?

_Introducing state transitions for temporal relationships.  That was an interesting and potentially valuable insight._

**Comment by tzimmermsr** [comment]
Moved to #71
