### ISSUE TITLE
Review of "Inductive Software Engineering: What we do IS Different"

### ISSUE THREAD

**Issue by andreas-zeller** [ds4se/chapters#121]
## Title of chapter

_ Inductive Software Engineering: What we do IS Different_
## URL to the chapter

_https://github.com/ds4se/chapters/blob/master/menzies/inductiveManifesto.md_
## Message?

What is the chapter's  clear and approachable take away message?

_Read the inductive software engineering manifesto (or don't, now that you have the summary)_
## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

_The summary of the inductive SE manifesto is great.  I won't comment on the manifesto itself, because if you change things, it wouldn't be a summary anymore, but as a summary, it works well._
## Size?

Is the chapter the right length?
Should anything missing be added?
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?
What are the aspects of the chapter that authors  SHOULD  change?

_I was not too happy with the introduction -- it starts with name-dropping, which gives it an insider-only flavor.  I would prefer a motivation stating why a term like "inductive SE" would be needed, or how it would delineate itself from, say, empirical SE.  Also, it wouldn't hurt to define the term "induction" before using it -- yes, I know what induction means in this context, but again, there's a lost chance to delineate the inductive approach to SE from, say, the deductive approach.  In that sense, the chapter does not really deliver (yet) on the promise given in the title, but could easily do so by positioning "inductive SE" clearly with respect to alternatives._
## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

_Inductive SE is way cool._
## Best Points

What are the best points of the chapter that the authors should NOT change?

_All from "Principle #1"._

**Comment by tzimmermsr** [comment]
Moved to #40
