### ISSUE TITLE
Review of " What Counts is Decisions, Not Numbers – Towards an Analytics Design Sheet" by Earl Barr

### ISSUE THREAD

**Issue by barr** [ds4se/chapters#124]
# Review
## Title of chapter

What Counts is Decisions, Not Numbers – Towards an Analytics Design Sheet
## URL to the chapter

[https://github.com/ds4se/chapters/blob/master/GunetherRuhe/RuheNayebi.md](https://github.com/ds4se/chapters/blob/master/GunetherRuhe/RuheNayebi.md)
## Message?

_What is the chapter's  clear and approachable take away message?_

Currently, most decisions in software engineering are made intutively.  This must change; more decisions must be made analytically;  this chapter describes an analystics design sheet whose adoption will transform decision-making.
## Accessible?

_Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?_

The chapter is indeed aimed at a generalist audience.

_How can it be made more accessible to generalist?_

Improve the illustrative example with more concrete detail, a point to which I return below.
## Size?

_Is the chapter the right length?_

I understand the lenght to be 4 pages, including references.  The current draft is one line over.

_What are the aspects of the chapter that authors  SHOULD  change?_

The example would be more helpful if it were more concrete;  specifically, if the nodes in the conceptual model were spelled out:  the letters E, S, and F are quite abstract.
### Copyedits

The following sentence parses poorly.

"This often implies delays in delivering products or lack of quality."

The problem is that one can distribute the gerund over the or, 
not the verb implies.  I suggest 

This often implies lack of quality or delays in delivering products.

Before the bullet list at the end of the introduction:  to-wards -> towards.

In the bulleted list, 

"likelihood to make" -> "likelihood of making"

"likelihood of avoiding to make" -> "likelihood of avoiding making"

still better would be 

"likelihood of avoiding a wrong decision"

The most important types of analytics are the ones least studied by researchers [5].

Citation abuse is making a citation that does not stand on its own, but requires the reader to consult the referenced work in detail to understand the citation.  Here, "important types" is vague;  why force the reader to read unnamed authors et al. [5] to learn what they are?

AHS -> ADS

Titles are not in title case.

Citations are not nouns.
## Gotta Mantra?

_We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here._

A checklist for software decisions

Supporting software decisions
## Best Points

In seeking to support decision making in software engineering, the authors are attacking a seminal, yet neglected software engineering problem.

**Comment by timm** [comment]
mentioned in #124 #23

**Comment by maleknaz** [comment]
Thanks for the very good comments. 

@barr 
- We changed the example to create more tangible demo. We removed the previous conceptual model and provided one which is more self-descriptive. 
- Typos and problems with citations are fixed.
