### ISSUE TITLE
./audris/ODIssues.org

### ISSUE THREAD

**Issue by tzimmermsr** [ds4se/chapters#127]
After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'.

Chapter leaves here:
https://github.com/ds4se/chapters/blob/master/audris/ODIssues.org

@timm

**Comment by tzimmermsr** [comment]
## Title of chapter

_Missing, Incorrect, and Decontextualized_

## URL to the chapter

_https://github.com/ds4se/chapters/blob/master/audris/ODIssues.org_

## Message?

What is the chapter's  clear and approachable take away message?
_Operational data is not as clean as experimental data_

## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?
_The chapter will be accessible to most_

## Size?

Is the chapter the right length?
Should anything missing be added?
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?
What are the aspects of the chapter that authors  SHOULD  change?

_I got lost in the "What to Do" section. It seems to be less connected to the previous section. Why the focus on only missing data? Why the focus on issue reports (and not say some other operational data)? The section reads a little bit like a laundry list. The What to Do has may examples what can go wrong, but not as much advice on what to actually do about it._

_Regarding structure: Consider moving the incorrect data and unidentified context examples to the end in the conclusion, e.g., introduce OD, say that missing data is a big issue with the aircraft data, present some examples from issue reports and what we can do about them (the what to do is important to not discourage people), then conclude that it's not just missing data which can cause issues but also incorrect data and unidentified context (use the example)_

_New paragraph before "In summary"_

_Delete the "According to Wikipedia"_

_A few typos_:
_how exactly data science => how exactly does data science_
_that only aircraft => aircrafts_
_issue reported by one person => issues_

## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.
_The title is not very catchy, maybe: How to get Operational Data right_

## Best Points

What are the best points of the chapter that the authors should NOT change?
_The discussion of three examples and how they related to software engineering is really good_

**Comment by timm** [comment]
# Review template

Before filling in this review, please read our [Advice to Reviewers](how2review.md).

_(If you have confidential comments about this chapter, please email them to one of the book editors._)

## Title of chapter

_Missing, Incorrect, and Decontextualized_

## URL to the chapter

_https://github.com/ds4se/chapters/blob/master/audris/ODIssues.org _

## Message?

What is the chapter's  clear and approachable take away message?

_sometimes, what is **NOT** there is most important_

## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

<em> The examples section is v. approachable but the "what to do" section is harder to read. Perhaps the errors with defect reports could be example4 in the examples section? then talk more to generalities in a final "what to do"?

</em>

## Size?

Is the chapter the right length?
Should anything missing be added?
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?
What are the aspects of the chapter that authors  SHOULD  change?

_The chapter is incomplete: references should all be in the readme file. _

## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

_the title needs work. The Data not is not in the Data? Why Context is so Important?_

## Best Points

What are the best points of the chapter that the authors should NOT change?

_The examples!_

**Comment by tzimmermsr** [comment]
@audris Please take a look at the reviews and prepare a new version of the chapter by January 13. Copy over the

**Comment by tzimmermsr** [comment]
@audrism Please take a look at the reviews and prepare a new version of the chapter by January 13. 

Please also think of a better title (see some suggestions in the reviews)

**Comment by audrism** [comment]
Thank you for great suggestions. I tried to restructure and clarify the todo part to the extent possible.

The references are in the pdf/bbl file, I am not so sure how to export that to md nor if thats the final format.

Also, aircraft is plural for aircraft :-)
