### ISSUE TITLE
end jan things to discuss with tom and laurie

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#133]
-  [x]  Q1: i've got this entry in the "perspectives book status" and i can't find the chapter. i think its one of the ones i did not get too. needed? OBE?
  Tim Menzies, Tom Zimmermann, Laurie WilliamsMerely Mining? Or Sharing Insight?
  - RESOLVED: we won't do this one
- [x]   Q2: i've revised our book chapter based on reviewer comments Perspectives on Data Science for Software Engineering. this chapter has all our names on it so please check.
  https://github.com/ds4se/chapters/blob/master/menzies/dagstuhlManifesto.md
- [x] Q3: @tzimmermsr Tom, you have not revised https://github.com/ds4se/chapters/commits/master/zimmermann/card-sorting.md. when please, good sir?
- [x] Q4: @tzimmermsr Tom, you have not revised https://github.com/ds4se/chapters/blob/master/zimmermann/no-one-size-fits-all.md when please, good sir?
- [x] Q5: Here are our current groupings. some to small, one too large (wisdom). any other ways to divide the book?

```
   1 Applications?
   1 People
   2 Misc
   4 Results
   5 Manifestos / Intro
   6 Success Stories
   9 Data
  19 Techniques
  23 Wisdom
```

**Comment by tzimmermsr** [comment]
@timm Regarding Q1: You moved he chapter under "badideasDoNotReview"
https://github.com/ds4se/chapters/blob/master/menzies/badideasDoNotReview/sharingManifesto.md
