### ISSUE TITLE
is this what was meant by "dagstuhl manifesto" or is this an intro cpahter 

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#4]
https://github.com/ds4se/chapters/blob/master/menzies/dagstuhlManifesto.md

**Comment by tzimmermsr** [comment]
I think that's better suited as an intro to the book (because it explains the why the book, etc.)

For the manifesto, I had in mind the contents of Section 3 of the Dagstuhl report. http://drops.dagstuhl.de/opus/volltexte/2014/4763/pdf/dagrep_v004_i006_p064_s14261.pdf

**Comment by timm** [comment]
Ok... another chapter.. i can do that.
