### ISSUE TITLE
./meinagappan/miningmobileappstores.md

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#53]
After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'.

**Comment by hongyujohn** [comment]
## Title of chapter

Mobile App Store Analytics

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/meinagappan/miningmobileappstores.md

## Message?

This chapter introduces the recent work on mining data from mobile app stores, which is an interesting research topic. The mined data could help address relevant software engineering issues, such as better understanding of end users and frequent complaints. 

## Accessible?

Yes, the chapter is written in an accessible manner, and is suitable for general audience.

## Size?

The size of the chapter is ok. However, the number of reference (23) is too many . 
This book is mainly for general audience (no excessive use of technical terminology) with a minimum of diagrams and references.  So this book chapter needs not to be a technical survey paper. I remember the editors have specified a limit for the number of references.

The authors may also describe the relationship between mobile app store analytics and software analytics in general.

## Gotta Mantra?

Yes.

## Best Points

Good descriptions about the concepts of mobile app store, mobile app store analytics, and an application of mobile store analytics in understanding end users. 

Good summarization of related work.

**Comment by timm** [comment]
From Nenad:

This was a fun chapter to read, but it suffers from three minor-to-moderate problems that, if addressed, would improve the chapter in my view.

MODERATE: The chapter is descriptive and clear in the treatment of the problem but does not contain actionable advice. What can I, either as a developer or user of mobile apps, do (better) as a result of the described mining exercise and subsequent analysis?

MODERATE: The chapter does not have a thesis statement up front nor a conclusion at the end. I found the last paragraph, which listed other things one could do with app repositories, distracting and out of place. I was expecting a punchline there. Along with the lack of actionable advice (issue #1), this made it look like more support for mining “because we can”.

MINOR: The following sentence struck me as a tautology: “For example, a 1 to 2 star ratio of 5 for a complaint type indicates that this complaint type has 5 times as many 1 star ratings as 2 star ratings.” I think it can easily be removed without loss of understandability or content. I think it would also be interesting to see, if you have the data, to what extent developers respond to the really negative comments in subsequent releases, and whether this, in turn, improves the given app’s reviews.

**Comment by timm** [comment]
I'm nodding with nenad: I was expecting a punchline there. 

It just sort of ... ends... without really a comment. e.g. will all software become app-based? will larger systems divide themselves up into lots of apps? is the push for devops naturally forcing all larger packages to become apps?

at the very least, what about the telemetry requirements of monitoring apps? what can we learn about the data storage amounts/data updates from apps (for devops for larger systems)? etc

**Comment by timm** [comment]
Thanks @meido :+1: Good to go
