### ISSUE TITLE
./miryungkim/datascientists.md

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#61]
After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'.

**Comment by meido** [comment]
## Title of chapter

How Data Scientists can Effectively Impact Organizations

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/miryungkim/datascientists.md

## Message?

Each subsection touches upon a key thing to consider before investing time and money on a data science project. 

## Accessible?

Yes. This is very accessible. 

Small typo fixes:
- "The most accurate is to ask everybody all the time. " Maybe change this sentence to make it clear about what should be most accurate?
- Maybe include a section called references in the bottom. And add your affiliation at the top. 
- close double quotes missing - "Technical Report MSR-TR-2015-30
- Some references have titles in quotes and others don't. 

## Size?

The size of the article seems to be good. If I were to add something then it would be a section on some things that were unexpected in their study. This could just been a cool addition. Not required though. 

## Gotta Mantra?

Dos and Don'ts of Data Science in a Software Company. 

## Best Points

Gives a succinct view on the experiences of data scientists + the example quotations adds a nice flair to it.

**Comment by emadshihab** [comment]
## Title of chapter

How Data Scientists can Effectively Impact Organizations

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/miryungkim/datascientists.md

## Message?

The chapter provides a practitioners perspective of the issues data scientists need to consider to make positive practical impacts. 

## Accessible?

The chapter is certainly accessible to a general audience. In addition, one really nice thing is the chapter is also technical enough to not be boring for a more technical audience. Kudos!

To improve, I would suggest adding a definition of data science, if possible.

## Size?

The chapter is the right size. As suggested above, I would a definition of data science. Also, it seems like the chapter is about data from software systems, hence, I would add that this is data science for 'software' organizations.

## Gotta Mantra?

I like the title, but perhaps re-framing it as a question may make it more interesting. Something like:
What do practitioners think about data science? or 
The Five Things You Need to Know About Data Science in Software Organizations.

Just suggestions, the current title is fine also.

## Best Points

I love the go the last mile subsection. It is so true!

**Comment by timm** [comment]
Good chapter.

**Comment by miryung** [comment]
updated version of the chapter is committed to the repository.

**Comment by timm** [comment]
@miryung thanks for the revision.

Totally optional, but here's an idea:
- Add a prefix to all your sub-headings: e.g. Step1: Choose the Right Questions for the Right Team
-  Remain the chapter: Five Steps for Success: How to  Deploy Data Science in Your Organizations 

Then tweak para1 just a little to say that "5 steps follow"

**Comment by miryung** [comment]
I have addressed Tim's comment and checked in a new version.
