### ISSUE TITLE
./obaysal/personalization-chapter.md

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#65]
After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'.

**Comment by kimherzig** [comment]
## Title of chapter

_A Tailored Suit: The Big Opportunity in Personalizing Issue Tracking_

## URL to the chapter

_https://github.com/ds4se/chapters/blob/master/obaysal/personalization-chapter.md_

## Message?

What is the chapter's  clear and approachable take away message?

_Bug tracking systems are too complex and too inflexible to suite the very different requirements of developers and their development processes and that customizing them would help people to use them more efficiently._

## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

_The chapter is very well suite for general audiance. No changes required._

## Size?

Is the chapter the right length?

_yes_

Should anything missing be added?
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?
What are the aspects of the chapter that authors  SHOULD  change?

_I think the chapter would benefit from saying a few words about more modern tracking systems such as Jira or even GitHub or Google trackers, which already give more context such as test runs etc. I think it would not even hurt to make the chapter a bit longer, so no other content would have to be removed. There might be an opprotunity to cross link to other chapters talking about noise and bias based on bug reports: another indication that the tools do not fit the processes. Lasst but not least, I was expecting a short dicussion about the fact that customization can lead to overfitting, meaning the tool has to change if we change the process. Therefore, using dashboards and views are a great way to simply blend out the stuff that the team does not use / need, at least at the moment._

## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

_Some suggestion: to make the analogy a bit better, the author could compare the different usually unused meta-data fields to too many pockets in a too big suite. And that the limitation of queries are like too short trousers that leave you in the cold no matter what. That would tie to content more to the matra. But this is just a suggestion. I like the tailored suite analogy._

## Best Points

What are the best points of the chapter that the authors should NOT change?

_The tailored suite analogy. Very valid point about bug trackers. The idea of views and dashboards--not changing the DB or the backend but what and how we present things._

**Comment by timm** [comment]
see also #104  

note that kim is asking for more details. e.g. why ISN'T the standard github analytics interface not good enough (or, to be kinder to github, say that its ok but here are a list of queries that we want to add to that interface).
