### ISSUE TITLE
./pgbovine/PreppingData.md

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#67]
After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'.

**Comment by obaysal** [comment]
# Review template

## Title of chapter

Practical tips for preparing your raw data for analysis

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/pgbovine/PreppingData.md

## Message?

What is the chapter's  clear and approachable take away message?

Invest your time in writing a robust parser to have your data ready for the analysis. 

## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

The chapter is well written; I liked the practical tips the author offered. 

## Size?

Is the chapter the right length?
Should anything missing be added?
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?
What are the aspects of the chapter that authors  SHOULD  change?

The chapter _feels_ to be a bit lengthy, although it is within the word limit. Also I'd suggest to use commas or semicolons at the end of each item in the lists (e.g., "logs from a Web server,") throughout the chapter.

## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

Needs a catchy title! May be "How to Write Your Parser for Fun and Win: Practical Tips"? Or a better one.

## Best Points

What are the best points of the chapter that the authors should NOT change?

Language and examples! It was an easy read; examples are simple and nice.

**Comment by alexorso** [comment]
# Review

## Title of chapter

Practical tips for preparing your raw data for analysis

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/pgbovine/PreppingData.md

## Message?

What is the chapter's  clear and approachable take away message?

There are many tips and tricks that can make the parsing and cleanup of raw data more efficient and effective.

## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

The chapter is very easy to read. It contains a little bit of technical lingo here and there, but anybody with some interest in this book should be able to read and understand it.

## Size?

Is the chapter the right length?
Should anything missing be added?
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?
What are the aspects of the chapter that authors  SHOULD  change?

I think the paper's length is appropriate. The presentation is fairly concise and never repeats concepts already covered.

Maybe the author could add some pointers to "standard" parsing tools (logstash? others?) that can be used to process raw data either as provided, for simple data sets, or as a starting point to build more complex parsers.

Maybe it is OK in this context, but I find the language a bit too colloquial. Some examples: “assert the heck out of your parsing code”, “Write assertions until your eyes bleed”, use of contractions, excessive use of exclamation marks. In general, the use of informal language seems a bit excessive and unmotivated, but  I will let the editors decide whether this is an issue. Except for that, the chapter is well written and enjoyable.

## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

The author did not go for a catchy title. I cannot really think of any very good one, though. Maybe just going for something concise and to the point would do: "Data parsing's tips and tricks".

## Best Points

What are the best points of the chapter that the authors should NOT change?

I like the author's concrete take on raw data parsing. The provided list of suggestions is not at all surprising, yet it is nice to have all these useful tips and guidelines in one place and described in a way that makes them immediately applicable. In short, I would not change the content.

**Comment by tzimmermsr** [comment]
@pgbovine Please prepare a final version of your paper by January 13 taking the reviewers' feedback into account. The length of the chapter is fine. Colloquial language is OK in the context, but you might want to tone down some of the sentences. 

In "Pipe stdout and stderr to log files" maybe add the syntax that pipes stdout and stderr to files, not everyone is familiar with it and it's not trivial to find on the Internet.

**Comment by pgbovine** [comment]
thanks for the helpful comments! I toned down the colloquial language, tried adding a more catchy title, and made other minor revisions as well.

**Comment by tzimmermsr** [comment]
Thanks @pgbovine for the revisions. It's good to go from my side.
