### ISSUE TITLE
./rtholmes/summarizing-dynamic-data.md

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#71]
After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'.

**Comment by tzimmermsr** [comment]
Adding Pete Rotella's Review.

## Title of chapter

_Summarizing Dynamic Data_

## URL to the chapter

_https://github.com/ds4se/chapters/blob/master/rtholmes/summarizing-dynamic-data.md_

## Message?

What is the chapter's  clear and approachable take away message?

_State transition diagrams can quickly yield useful information in temporal data.  Bikeshedding is normal and tempting, but the next step can be a high-level summarization (prior to more detailed examination) that can be useful._

## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

_The text prior to the state transition diagrams is fairly clear and understandable to the non-expert, but the state transition diagrams are not understandable to the non-expert.  The nomenclature is specific to code review practitioners of the two tools, Webkit and Firefox CR tools.  More generally understandable nomenclature would be needed for a non-expert to fully appreciate the point he is raising._

## Size?

Is the chapter the right length?
Should anything missing be added?
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?
What are the aspects of the chapter that authors  SHOULD  change?

_The diagram needs to be explained better, as mentioned above._

## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

_The title is OK.  Maybe change it up a little with something like 'state-transition diagramming – a useful approach.'_

## Best Points

What are the best points of the chapter that the authors should NOT change?

_I think both the bikeshedding and summarizing temporal data parts are good, with the exception of the diagram, which needs clarification._

**Comment by tzimmermsr** [comment]
Review by @andreas-zeller (moved from #120)

## Title of chapter

Summarizing Dynamic Data

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/rtholmes/summarizing-dynamic-data.md

## Message?

What is the chapter's  clear and approachable take away message?

_To summarize dynamic data, consider state transitions_

## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

_I am not sure whether the problem of bike shedding in empirical SE is sufficiently widespread to warrant this chapter; so more evidence and/or motivation would be welcome.  Likewise, I am not sure whether the solution of summarizing data into state transitions is sufficiently general to be framed as the one solution.  I would prefer having a concrete story (which is currently hidden in the chapter) on how state transitions saved a particular concrete project._

## Size?

Is the chapter the right length?
Should anything missing be added?
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?
What are the aspects of the chapter that authors  SHOULD  change?

_See above.  I can live with the chapter as is, but making it more of an anecdote would be both more compelling and justified._

## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

_Look for State Transitions in Temporal Data_

## Best Points

What are the best points of the chapter that the authors should NOT change?

_Introducing state transitions for temporal relationships.  That was an interesting and potentially valuable insight._

**Comment by tzimmermsr** [comment]
@rtholmes Please prepare a new version of the chapter taking the reviewer's feedback into account, in particular explaining the diagrams better and showing how they could be used in practice.

**Comment by tzimmermsr** [comment]
(forgot to add the date) @rtholmes Please prepare a new version of the chapter by January 13.

**Comment by rtholmes** [comment]
Sorry, I updated this a few days ago but forgot to change the label.

**Comment by tzimmermsr** [comment]
Thanks for making the changes @rtholmes. I have two smaller requests, then the chapter is good to go from my side.
- [ ] Please choose a catchy title. Both Pete and Andreas offer good candidates, e.g., "Look for State Transitions in Temporal Data" or "To summarize dynamic data, consider state transitions"
- [ ] In the paragraph, where you describe the state diagrams ("We next examined how the code reviews move between the states; ..."), please add what the percentages on the edges means.

Thanks,
Tom

**Comment by tzimmermsr** [comment]
@rtholmes Did you have a chance to look at the two small change requests. They should take you only 10-15 minutes and then we can send of your chapter to MK. :-)

Thanks,
Tom

**Comment by rtholmes** [comment]
@tzimmermsr; I missed the original notification. Changes made!

**Comment by rtholmes** [comment]
See https://github.com/ds4se/chapters/commit/3dfb068c4d362ad56947b27c2aa01b31bdb47baf

**Comment by tzimmermsr** [comment]
Thanks @rtholmes . This is good to go. 

@timm I've updated the Perspective Book Status with new title and status.
