### ISSUE TITLE
./weyuker-ostrand/prediction.md

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#88]
After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'.

**Comment by maoivo** [comment]
## Title of chapter

Identifying Fault-prone Files in Large Industrial Software Systems

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/weyuker-ostrand/prediction.md

## Message?

This is a story about how the authors developed methods and tool for fault prediction over several years of research with large industrial software systems.

## Accessible?

The story is very easy to read by generalists and does not require special knowledge.

## Size?

Is the chapter the right length? Yes
Should anything missing be added? Yes, fault prediction in general.
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).? The story of how the algorithms and tools were developed could be much shorter.
What are the aspects of the chapter that authors  SHOULD  change?

The chapter is very well written and easy to read. It deals with practical industrial software systems. However, it could also give the readers concrete knowledge about fault prediction in general, not only the story about how the authors developed their fault prediction methods and tool.

## Gotta Mantra?

No.

## Best Points

Well-written chapter about an important topic

**Comment by tzimmermsr** [comment]
Review by @GRuhe (copied from #110)

## URL to the chapter

_the markdown file. e.g. https://github.com/ds4se/chapters/blob/master/weyuker-ostrand/prediction.md_

## Message?

What is the chapter's  clear and approachable take away message?

_Accurate defect prediction IS possible_

## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

_Yes, it is written in a non-technical language, easy to understand also for non-experts_

## Size?

Is the chapter the right length?
Should anything missing be added?
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?
What are the aspects of the chapter that authors SHOULD  change?

_Length is right, no suggestion for changes. Would be nice to have one or two sentences if and how successful the results were used at AT&T._

## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

_Fault distribution among files follows the Pareto rule_

## Best Points

What are the best points of the chapter that the authors should NOT change?

_Starting with a (nice and to-the point) joke_

**Comment by tzimmermsr** [comment]
Great chapter @tostrand! It's a great retrospective on how to build successful defect prediction models. 

Please prepare a final version of your paper by January 13 taking the reviewers' feedback into account. I agree with @GRuhe that it "Would be nice to have one or two sentences if and how successful the results were used at AT&T."
